name: 'GitHub-CI: lint & test'

on:
    push:
        branches:
            - master
    pull_request: {}
jobs:
    setup:
        name: Checkout & Install
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node: [12,14]
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2

            - name: Setup node
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node }}

            - name: 📥 Download deps
              uses: bahmutov/npm-install@v1
              with:
                  useLockFile: false
    lint:
        needs: setup
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node: [12,14]
        steps:
            - name: Run lint
              run: |
                  npm run lint
    flow:
        needs: setup
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node: [12,14]
        steps:
            - name: Run Lint
              run: |
                  npm run lint

            - name: Run Flow Typed
              run: |
                  npm run flow-typed && npm run flow
    karma:
        needs: setup
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node: [12,14]
        steps:
            - name: Run karma
              run: |
                  npm run karma
