name: 'GitHub-CI: Lint & Test'

on:
    push:
        branches:
            - master
    pull_request: {}
jobs:
    lint:
        name: Run Lint
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node: [10,12,14]
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2

            - name: Setup node
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node }}

            - name: 📥 Download deps
              uses: bahmutov/npm-install@v1
              with:
                  useLockFile: false
            - name: Run lint
              run: |
                  npm run lint
    flow:
        name: Run Flow
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node: [10,12,14]
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2

            - name: Setup node
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node }}

            - name: 📥 Download deps
              uses: bahmutov/npm-install@v1
              with:
                  useLockFile: false
            - name: Run Flow Typed
              run: |
                  npm run flow-typed && npm run flow
    karma:
        name: Run Karma
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node: [10,12,14]
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2

            - name: Setup node
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node }}

            - name: 📥 Download deps
              uses: bahmutov/npm-install@v1
              with:
                  useLockFile: false

            - name: Run karma
              run: |
                  npm run karma
